### ISSUE TITLE
docker-compose pull & latest-arm build

### ISSUE THREAD

**Issue by felixmueller** [rursache/bird.makeup#1]
@rursache Thank you very much for mirroring! I have 2 questions:

1. How can I pull your docker image with docker-compose? The original image is named cloutier/bird.makeup:latest or cloutier/bird.makeup:latest-arm. How is the image specified in your case?
2. cloutier provided an arm64 build, which I am using on my low powered arm machine. Could you update your workflow to also publish the "latest-arm" version of the image? Thank you so much!

**Comment by rursache** [comment]
There are no arm64 builds at this time, not sure if github can build those

**Comment by felixmueller** [comment]
@rursache GitHub can build arm images, see here for example: https://github.com/videah/SkyBridge/blob/master/.github/workflows/docker.yml

**Comment by rursache** [comment]
i'll take a look when i have the time for it

**Comment by rursache** [comment]
arm64 builds are now included in each release
