### ISSUE TITLE
Missing object definition on POST  inbox

### ISSUE THREAD

**Issue by hieronymousch** [rursache/bird.makeup#4]
Hi,

Every time that there happens a POST on /user/inbox I get a nice error: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'BirdsiteLive.ActivityPub.ActivityFollow' does not contain a definition for 'object'

Have you encountered this before? I've been trying a lot of different approaches and keep on having this issue. 
My instance now fakes that you can follow it but than removes/looses it's followers.

Thanks in advance

**Comment by rursache** [comment]
@hieronymousch make sure to follow the steps written [here](https://github.com/rursache/bird.makeup/issues/3)

if you keep having issues, [contact the original developer](https://sr.ht/~cloutier/bird.makeup) directly, this is just a repo mirror
